### ISSUE TITLE
Alloy Forgery Support

### ISSUE THREAD

**Issue by ardissaps** [Luligabi1/FuelInfo#1]
[Alloy Forgery Support](https://modrinth.com/mod/alloy-forgery), Thank you very much!
![image](https://user-images.githubusercontent.com/82106625/177494566-0c6adc01-861b-4409-a905-a9931d912dce.png)

**Comment by Luligabi1** [comment]
I'm not planning adding any sort of mod support as of right now as, but you might have better luck asking the project owners to add it themselves, it's not very complicated to do so.
