### ISSUE TITLE
Compatibility for Roughly Enough Items

### ISSUE THREAD

**Issue by sternschnaube** [Luligabi1/FuelInfo#12]
### FuelInfo version

FuelInfo-2.0+1.20.5.jar

### Mod Loader

Fabric

### Modloader version

0.15.11

### Minecraft Version

1.20.6

### The latest.log file

/

### Describe your issue

Small graphical issue.

![image](https://github.com/Luligabi1/FuelInfo/assets/120551916/80bcf8a2-74fa-40b9-af00-32d3ef394e0d)

![image](https://github.com/Luligabi1/FuelInfo/assets/120551916/ff4b8a29-7b24-40c0-ba2d-36d74b585f92)

**Comment by Luligabi1** [comment]
I've added a config that allows choosing whether fuel data and the timer can appear on either flame or progress arrow; To fix your issue, you'd only need to disable the timer from appearing on the progress arrow and allow it to appear on the flame, all within the Modmenu-integrated config screen.

The code is ready, although I'll have to wait for the config library to fix an issue with Neoforge before publishing; I'll reply again when it's available!

**Comment by sternschnaube** [comment]
Bravo, thank you 😊

**Comment by Luligabi1** [comment]
@sternschnaube version `2.1+1.20.6` is out now at Modrinth, should be approved on Curse soon. Thanks for reporting!

**Comment by sternschnaube** [comment]
Thanks!!
