### ISSUE TITLE
Add repo description on github (on the right side)

### ISSUE THREAD

**Issue by Goldenlion5648** [Luligabi1/FuelInfo#13]
### Describe your idea

I found the mod through the [modtoberfest site](https://modtoberfest.com/repositories)

There was no description for this mod. I recommend adding a description (on the right side on github).

May I suggest:
`Displays extended info on vanilla Furnaces (including its variants) and Brewing Stands, such as how many items can be smelted, time remaining and how many (sets of) potions can be brewed.`

**Comment by Luligabi1** [comment]
Uh, sure. FYI, only pull requests count toward Modtoberfest's rewards 🙂

**Comment by Goldenlion5648** [comment]
Yeah I know 🙂(I was originally trying to do this as a pull request in another repo, but apparently you can't merge description from another repo)
