### ISSUE TITLE
Incorrect values for consumed fuel

### ISSUE THREAD

**Issue by CaphalorAlb** [Luligabi1/FuelInfo#9]
hey! I think i might have run into a bug

The issue is as follows:
- when i hover over the flame of the furnace with fuel in the slot it shows the correct number. (nothing smelting)
- when i start smelting, one item is consumed and it shows an incorrect number
- the relation seems to be: n*x+x where x is the fuel value for one item (eg coal)

example (with attached pictures) 2 coal correctly show as 16 items
when smelting starts, it incorrectly shows as 24 items and counts down from there
![2023-09-24_12 37 50](https://github.com/Luligabi1/FuelInfo/assets/73060258/016c2179-0780-4fbd-af0d-38f743732e32)
![2023-09-24_12 38 53](https://github.com/Luligabi1/FuelInfo/assets/73060258/00bc1304-39b1-4f81-8e49-7391698a3682)

so it seems, that the "currently burning" value is off by a factor of 2

this only affects the furnace, blast furnace and smoker are not affected

I tested this with a fresh instance, only fabric and fuelinfo mods added, hopefully you can reproduce it

FuelInfo Version: 1.0.4
Minecraft: 1.20.1
Fabric: 0.14.22
Fabric API: 0.89.0+1.20.1

**Comment by Luligabi1** [comment]
Fixed in `1.1.0+1.20.1`
